/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.rolliff.asb;

import org.junit.jupiter.api.Test;

class AppTest
{
  @Test
  void appHasAGreeting()
  {
    App classUnderTest = new App();

  }
}
